# ============================================================================
# DEPLOYMENT STRATEGY: SD Card Boot + Btrfs RAID0 NVMe Storage
# ============================================================================
#
# CONFIGURATION:
# - SD card for EFI boot partition (simple, reliable)
# - Btrfs RAID0 on dual NVMe drives for system storage (performance)
# - Metadata mirrored (RAID1) for filesystem safety on NVMe array
#
# NOTE: Disk names are chosen for alphabetical processing order:
# boot -> data-member -> main (RAID0 requires first partition to exist)
#
# Subvolumes (@nix, @permafrost, @log) are generated by mountainous.impermanence
# ============================================================================
{
  disko.devices = {
    disk = {
      # SD Card - 32GB (Boot)
      boot = {
        type = "disk";
        device = "/dev/disk/by-id/mmc-SD32G_0xfcf357fa";
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = "2G";
              type = "EF00"; # EFI System Partition
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = ["umask=0077"];
              };
            };
          };
        };
      };

      # NVMe Drive 1 - WD Blue SN570 2TB (Btrfs RAID0 member)
      # Named "data-member" to sort before "main" alphabetically
      data-member = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-WD_Blue_SN570_2TB_22343V800890";
        content = {
          type = "gpt";
          partitions = {
            root = {
              size = "100%";
              # Empty - btrfs RAID defined on main disk
            };
          };
        };
      };

      # NVMe Drive 2 - WD Blue SN570 2TB (Btrfs RAID0 with subvolumes)
      # Named "main" to match impermanence defaults (processes after data-member)
      main = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-WD_Blue_SN570_2TB_22343V800725";
        content = {
          type = "gpt";
          partitions = {
            root = {
              size = "100%";
              content = {
                type = "btrfs";
                extraArgs = [
                  "-f"
                  "-d raid0" # Data striped for performance
                  "-m raid1" # Metadata mirrored for safety
                  "/dev/disk/by-id/nvme-WD_Blue_SN570_2TB_22343V800890-part1" # data-member partition
                ];
                # Subvolumes generated by mountainous.impermanence feature
              };
            };
          };
        };
      };
    };
  };
}
