# Example home-manager module
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.modules.my-home-manager-module;
in {
  options.modules.my-home-manager-module = {
    enable = mkEnableOption "my home-manager module";

    setting = mkOption {
      type = types.str;
      default = "default value";
      description = "An example setting for the module.";
    };
  };

  config = mkIf cfg.enable {
    # Module implementation goes here
    home.packages = with pkgs; [
      # Example packages this module might add
      ripgrep
      fd
    ];

    # Add module-specific configuration
    home.file.".config/my-module/config".text = ''  
      # Generated by NixOS
      setting = ${cfg.setting}
    '';
  };
}
