# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      ../modules/workstation.nix
      ../modules/wireguard-client.nix
      ./default.nix
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  services.xserver.extraConfig = ''
    Section "Device"
      Identifier "intelgpu0" 
      Driver "intel"
      Option "VirtualHeads" "2"
    EndSection
  '';

  services.xserver.deviceSection = ''
    Option "VirtualHeads" "2"
    Option "TearFree" "true"
  '';

  services.xserver.exportConfiguration = true;
  services.xserver.videoDrivers = [ "intel" ];
  # services.xserver.useGlamor = true;

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/7a871b00-0277-4ced-9203-7a392436b972";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/14F9-7A1C";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/570cb165-8a3b-4583-8750-d0b0aa94c775"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking.wireguard.interfaces = {
    mtn = {
      ips = [ "192.18.2.12/32" ];
      privateKey = builtins.getEnv "WIREGUARD_YARI_PRIVATE";
    };
  };
}
