# Dependencies provided by writeShellApplication in default.nix

set -euo pipefail

DEFAULT_ARCH="x86_64-linux"
DEFAULT_USERNAME="simonwjackson"
BASE_DIR="$(git rev-parse --show-toplevel)"
SECRETS_FILE="${BASE_DIR}/secrets/default.nix"
SSH_KEY=""
ARCH="$DEFAULT_ARCH"
USER_PUBKEY=""
CAPTURE_TARGET=""


show_usage() {
  echo "Usage: scaffold [username@]<system-name> [--arch <architecture>] [--identity <ssh-key-path>] [--capture <ssh-target>]"
  echo "Default architecture: $DEFAULT_ARCH"
  echo "Default username: $DEFAULT_USERNAME"
  echo ""
  echo "  --capture <ssh-target>   Adopt a host whose SSH host key already exists."
  echo "                           Reads /etc/ssh/ssh_host_rsa_key.pub via SSH from"
  echo "                           <ssh-target> instead of generating a new keypair"
  echo "                           locally. Skips writing the encrypted private key"
  echo "                           (since the host already owns it)."
  echo "                           Example: scaffold sobo --capture root@sobo"
  exit 1
}

check_ssh_key() {
  local default_keys=("$HOME/.ssh/id_ed25519" "$HOME/.ssh/id_rsa")

  if [ -z "$SSH_KEY" ]; then
    for key in "${default_keys[@]}"; do
      if [ -f "$key" ]; then
        SSH_KEY="$key"
        break
      fi
    done
  fi

  if [ -z "$SSH_KEY" ] || [ ! -f "$SSH_KEY" ]; then
    echo "Error: SSH key not found. Use --identity to specify one."
    exit 1
  fi

  USER_PUBKEY="${SSH_KEY}.pub"
  if [ ! -f "$USER_PUBKEY" ]; then
    echo "Error: SSH public key '$USER_PUBKEY' not found"
    exit 1
  fi

  echo "Using SSH key: $SSH_KEY"
}

create_config() {
  local dir="$1"
  local file="$2"
  local content="$3"

  if [ ! -f "$file" ]; then
    echo "Creating $file..."
    mkdir -p "$dir"
    printf '%s\n' "$content" >"$file"
    git add "$file"
  elif [[ "$file" == *.nix ]]; then
    echo "Nix configuration file already exists: $file"
  fi
}

parse_system_arg() {
  local arg="$1"
  local username_var="$2"
  local system_var="$3"

  if [[ "$arg" == *"@"* ]]; then
    printf -v "$username_var" "%s" "${arg%%@*}"
    printf -v "$system_var" "%s" "${arg#*@}"
  else
    printf -v "$username_var" "%s" "$DEFAULT_USERNAME"
    printf -v "$system_var" "%s" "$arg"
  fi
}

generate_host_keys() {
  local hostname="$1"
  local host_key_enc="${BASE_DIR}/secrets/keys/hosts/${ARCH}_${hostname}_ssh_host_rsa_key.age"
  local host_key_pub="${host_key_enc%.age}.pub"

  echo "Checking host keys for $hostname..."
  if [ -f "$host_key_enc" ] && [ -f "$host_key_pub" ]; then
    echo "Host keys already exist for $hostname"
    return 0
  fi
  if [ -z "$CAPTURE_TARGET" ] && [ -f "$host_key_pub" ]; then
    echo "Captured host pubkey already exists for $hostname (no .age private key)"
    return 0
  fi

  if [ -n "$CAPTURE_TARGET" ]; then
    capture_host_keys "$hostname" "$host_key_pub"
    return 0
  fi

  echo "Generating new host keys for $hostname..."

  local temp_dir
  local temp_key
  temp_dir=$(mktemp -d)
  temp_key="${temp_dir}/ssh_host_rsa_key"

  ssh-keygen -t rsa -b 4096 -f "$temp_key" -N "" -C "host-key-${hostname}" >/dev/null

  age --encrypt \
    --recipient "$(cat "$USER_PUBKEY")" \
    --output "$host_key_enc" \
    "$temp_key"
  cp "${temp_key}.pub" "$host_key_pub"

  rm -rf "$temp_dir"
  git add "$host_key_enc" "$host_key_pub"
}

# Adopt an existing running host: SSH to it, read its already-deployed RSA host
# pubkey, and persist only the .pub file. The host already owns its private
# key so we deliberately do not write a .age file. This is the right path for
# devices whose host keys were auto-generated by a substrate we do not own
# (e.g. sobo's nspawn guest, or a pre-existing install we are adopting into
# mountainous).
capture_host_keys() {
  local hostname="$1"
  local host_key_pub="$2"

  echo "Capturing host pubkey for $hostname from $CAPTURE_TARGET..."
  if ! ssh -o BatchMode=yes -o ConnectTimeout=10 "$CAPTURE_TARGET" \
        'cat /etc/ssh/ssh_host_rsa_key.pub 2>/dev/null || sudo -n cat /etc/ssh/ssh_host_rsa_key.pub' \
        > "$host_key_pub".tmp 2>/dev/null; then
    rm -f "$host_key_pub".tmp
    echo "Error: could not read /etc/ssh/ssh_host_rsa_key.pub from $CAPTURE_TARGET" >&2
    echo "       SSH access must be passwordless and the file must be readable" >&2
    echo "       (directly or via passwordless sudo)" >&2
    exit 1
  fi
  if ! grep -q '^ssh-rsa ' "$host_key_pub".tmp; then
    rm -f "$host_key_pub".tmp
    echo "Error: captured content does not look like an ssh-rsa pubkey" >&2
    exit 1
  fi
  mv "$host_key_pub".tmp "$host_key_pub"
  git add "$host_key_pub"
  echo "Captured: $(cut -c1-50 < "$host_key_pub")..."
}

update_secrets_nix() {
  local hostname="$1"
  local host_key_pub="${BASE_DIR}/secrets/keys/hosts/${ARCH}_${hostname}_ssh_host_rsa_key.pub"

  if [ ! -f "$SECRETS_FILE" ]; then
    echo "Error: ${SECRETS_FILE} not found"
    exit 1
  fi

  if [ ! -f "$host_key_pub" ]; then
    echo "Error: Host public key not found: $host_key_pub"
    exit 1
  fi

  echo "Updating ${SECRETS_FILE} for ${hostname}..."

  local pubkey
  pubkey="$(cat "$host_key_pub")"

  # Add host key variable if not already present (exact match on variable name)
  if ! grep -qE "^[[:space:]]+${hostname}[[:space:]]*=" "$SECRETS_FILE"; then
    # Insert before simonwjackson
    sed -i "/^[[:space:]]*simonwjackson[[:space:]]*=/i\\  ${hostname} = \"${pubkey}\";" "$SECRETS_FILE"
    echo "  Added ${hostname} key variable"
  else
    echo "  ${hostname} key variable already exists"
  fi

  # Add host to allKeys if not already present (word-boundary match)
  if ! grep -q "allKeys.*[[:space:]]${hostname}[[:space:]]" "$SECRETS_FILE"; then
    sed -i "s/ simonwjackson\]/ ${hostname} simonwjackson]/" "$SECRETS_FILE"
    echo "  Added ${hostname} to allKeys"
  else
    echo "  ${hostname} already in allKeys"
  fi

  git add "$SECRETS_FILE"
}

generate_syncthing_keys() {
  local hostname="$1"
  local host_pubkey_file="${BASE_DIR}/secrets/keys/hosts/${ARCH}_${hostname}_ssh_host_rsa_key.pub"
  local secret_dir="${BASE_DIR}/secrets/hosts/${hostname}"
  local encrypted_key="${secret_dir}/syncthing-key.age"
  local encrypted_cert="${secret_dir}/syncthing-cert.age"

  mkdir -p "$secret_dir"

  if [ -f "$encrypted_key" ] && [ -f "$encrypted_cert" ]; then
    echo "Syncthing secrets already exist for ${hostname}"
    git add "$secret_dir" 2>/dev/null || true
    return 0
  fi

  local temp_dir
  local key_path
  local cert_path
  temp_dir=$(mktemp -d)
  key_path="${temp_dir}/device.key"
  cert_path="${temp_dir}/cert.pem"

  echo "Generating Syncthing identity for $hostname..."
  openssl ecparam -genkey -name secp521r1 -noout -out "$key_path"
  openssl req -new -x509 -key "$key_path" -out "$cert_path" -days 3650 -subj "/CN=syncthing"

  # Encrypt for all keys (host + user) — secrets/default.nix auto-discovery
  # handles the agenix wiring; we just need the files to exist.
  age --encrypt \
    --recipient "$(cat "$host_pubkey_file")" \
    --recipient "$(cat "$USER_PUBKEY")" \
    --output "$encrypted_key" \
    "$key_path"

  age --encrypt \
    --recipient "$(cat "$host_pubkey_file")" \
    --recipient "$(cat "$USER_PUBKEY")" \
    --output "$encrypted_cert" \
    "$cert_path"

  rm -rf "$temp_dir"
  git add "$encrypted_key" "$encrypted_cert"
}

# ── Argument parsing ─────────────────────────────────────────────────

if [ $# -lt 1 ]; then
  show_usage
fi

# shellcheck disable=SC2034  # set via printf -v indirection
USERNAME=""
SYSTEM_NAME=""
parse_system_arg "$1" USERNAME SYSTEM_NAME

shift
while [[ $# -gt 0 ]]; do
  case $1 in
    --arch)
      ARCH="$2"
      shift 2
      ;;
    --identity)
      SSH_KEY="$2"
      shift 2
      ;;
    --capture)
      CAPTURE_TARGET="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

check_ssh_key

# ── Host config ──────────────────────────────────────────────────────

HOST_CONFIG=$(
  cat <<EOF
{lib, ...}: {
  imports = [
    # ./disko.nix
    # ./hardware.nix
  ];

  networking.hostName = "${SYSTEM_NAME}";
  time.timeZone = "America/Denver";

  nixpkgs.config.allowUnfree = true;

  mountainous = {
    presets.core.enable = true;
    presets.server.enable = true;

    features.device = {
      role = "portable";
      capabilities = {
        battery = false;
        formFactor = "desktop";
        touchscreen = false;
      };
    };
  };

  system.stateVersion = "26.05";
}
EOF
)

create_config \
  "${BASE_DIR}/hosts/${SYSTEM_NAME}" \
  "${BASE_DIR}/hosts/${SYSTEM_NAME}/default.nix" \
  "$HOST_CONFIG"

# ── Secrets & keys ───────────────────────────────────────────────────

generate_host_keys "$SYSTEM_NAME"
update_secrets_nix "$SYSTEM_NAME"
generate_syncthing_keys "$SYSTEM_NAME"

# ── Rekey if secrets are out of sync with allKeys ──────────────────

check_needs_rekey() {
  # Count keys in allKeys
  local expected
  expected=$(grep 'allKeys = \[' "$SECRETS_FILE" | tr '[]' ' ' | tr ';' ' ' | xargs -n1 | grep -cv '^\(allKeys\|=\)$' || true)

  # Pick the first .age file and count recipient stanzas
  local sample_age
  sample_age=$(find "${BASE_DIR}/secrets" -name '*.age' -not -path '*/keys/*' -not -path '*/archived/*' -print -quit)

  if [ -z "$sample_age" ]; then
    echo "false"
    return
  fi

  local actual
  actual=$(grep -c '^-> ' "$sample_age" || true)

  if [ "$actual" -lt "$expected" ]; then
    echo "true"
  else
    echo "false"
  fi
}

if [ "$(check_needs_rekey)" = "true" ]; then
  echo ""
  echo "🔑 Secrets have fewer recipients than allKeys — re-encrypting..."
  ids=()
  for k in "$HOME/.ssh/id_rsa" "$HOME/.ssh/id_ed25519" \
           /etc/ssh/ssh_host_ed25519_key /etc/ssh/ssh_host_rsa_key; do
    [ -r "$k" ] && ids+=(-i "$k")
  done
  if [ ${#ids[@]} -eq 0 ]; then
    echo "⚠️  No identity files found — skipping rekey. Run 'nix run .#secrets -- rekey' manually."
  else
    RULES="$SECRETS_FILE" agenix -r "${ids[@]}"
    git add "${BASE_DIR}/secrets/"
    echo "✅ Rekey complete"
  fi
else
  echo "All secrets already encrypted for all keys — rekey not needed"
fi

echo ""
echo "✅ Successfully scaffolded host ${SYSTEM_NAME}"
echo ""
echo "Next steps:"
echo "  1. Add ${SYSTEM_NAME} to flake.nix nixosConfigurations:"
echo "       ${SYSTEM_NAME} = mkHost {"
echo "         system = \"${ARCH}\";"
echo "         hostPath = ./hosts/${SYSTEM_NAME};"
echo "       };"
echo "  2. Create hosts/${SYSTEM_NAME}/hardware.nix and hosts/${SYSTEM_NAME}/disko.nix"
echo "  3. Commit and deploy: nix run .#deploy -- ${SYSTEM_NAME} <user@ip>"
