# NOTE: this file was generated by the Mobile NixOS installer.
{ config, lib, pkgs, ... }:

{
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/bfc45b06-3c3c-4c33-a863-6b9996f4ed2a";
      fsType = "ext4";
    };
  };

  nix.settings.max-jobs = lib.mkDefault 2;
}
