# Example NixOS module
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.modules.my-nixos-module;
in {
  options.modules.my-nixos-module = {
    enable = mkEnableOption "my nixos module";

    setting = mkOption {
      type = types.str;
      default = "default value";
      description = "An example setting for the module.";
    };
  };

  config = mkIf cfg.enable {
    # Module implementation goes here
    environment.systemPackages = with pkgs; [
      # Example packages this module might add
      htop
      curl
    ];

    # Add module-specific configuration
    environment.etc."my-module/config".text = ''  
      # Generated by NixOS
      setting = ${cfg.setting}
    '';
  };
}
